services:
  minio-mcphub:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio-mcphub
    ports:
      - "9010:9000"   # S3 API endpoint
      - "9011:9001"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Quarkus123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mcphub
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio_mcphub:9000 admin Quarkus123 &&
      mc mb local/documentation || true &&
      mc policy set public local/documentation
      "
    networks:
      - mcphub
# milvus
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mcphub
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mcphub
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.8
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9191/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9191:9191"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - mcphub
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Quarkus123
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/postgres:/docker-entrypoint-initdb.d
    networks:
      - mcphub
  adminer:
    image: adminer
    restart: always
    ports:
      - 8097:8080
    networks:
      - mcphub
  rabbitmq:
    image: rabbitmq:4-management
    hostname: data-fetch
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_NODENAME: rabbit@data-fetch
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbit-mq/rabbit_data-fetch.json:/etc/rabbitmq/definitions.json:ro
      - ./config/rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    restart: always
    networks:
      - mcphub

volumes:
  minio_data:
  pgdata:
  rabbitmq_data:

networks:
  mcphub:
    driver: bridge